name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Archive the dist folder
      run: tar -czf dist.tar.gz dist

    - name: Upload dist artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download dist artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Extract dist artifact
      run: tar -xzf dist/dist.tar.gz -C .

    - name: Copy dist to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./dist/ ./package.json"
        target: "/home/aup_bot_user/bot/dist"

    - name: Execute commands on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/aup_bot_user/bot
          nvm use 22
          node -v
          npm install --production
          npx pm2 restart 0
