name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Archive dist and package.json
      run: tar -czf deploy.tar.gz dist package.json

    - name: Upload deploy artifact
      uses: actions/upload-artifact@v3
      with:
        name: deploy
        path: deploy.tar.gz
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download deploy artifact
      uses: actions/download-artifact@v3
      with:
        name: deploy
        path: deploy

    - name: Extract deploy artifact
      run: tar -xzf deploy/deploy.tar.gz -C .
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name : verify content
      run: tree -a
    - name: Copy Dist and Config to Server
      run: |
        scp -r ./dist ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/aup_bot_user/bot
        scp ./package.json ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/aup_bot_user/bot


    - name: Execute command on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/aup_bot_user/bot
          nvm use 22
          node -v
          npm install --production
          npx pm2 restart 0
